# -----------------------------------------------------------------------------
# Minimal Site Settings for GitHub Pages
# -----------------------------------------------------------------------------

title: Ivan Rudik
first_name: Ivan
last_name: Rudik
description: Ivan Rudik - Cornell University

lang: en
icon: ⚛️

url: https://irudik.github.io
baseurl: ""

# -----------------------------------------------------------------------------
# Theme
# -----------------------------------------------------------------------------

# code highlighter theme
highlight_theme_light: github
highlight_theme_dark: native

# -----------------------------------------------------------------------------
# Layout
# -----------------------------------------------------------------------------

navbar_fixed: true
footer_fixed: true
max_width: 800px

# -----------------------------------------------------------------------------
# Social integration
# -----------------------------------------------------------------------------

github_username: irudik
twitter_username: ivanjrudik

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------

collections:
  news:
    output: true
    permalink: /news/:path/
  projects:
    output: true
    permalink: /projects/:path/

# -----------------------------------------------------------------------------
# Jekyll configuration - MINIMAL PLUGINS ONLY
# -----------------------------------------------------------------------------

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

# NO EXTERNAL PLUGINS - Using only GitHub Pages supported plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - bin/
  - README.md
  - LICENSE
  - CONTRIBUTING.md
  - docker-compose.yml
  - Dockerfile